### ISSUE TITLE
Проблемы с кастомизацией

### ISSUE THREAD

**Issue by koninka** [gillbeits/commerceml#12]
Доброго времени суток.

Пришлось скопипастить много кода, чтобы как-то кастомизировать для доп. полей ваш код.

Зачем в Factory использовать self, когда можно static и легко унаследоваться и собрать доп. поля (путем изменения класса модели оверрайдингом моделей в objects).
Негибко реализовано изменение классов моделей (Product, Offer и т.д.).

P.S. Удобная либа, но для базовых задач. Нужно добаивить больше гибкости.

**Comment by gillbeits** [comment]
> Доброго времени суток.
> 
> Пришлось скопипастить много кода, чтобы как-то кастомизировать для доп. полей ваш код.
> 
> Зачем в Factory использовать self, когда можно static и легко унаследоваться и собрать доп. поля (путем изменения класса модели оверрайдингом моделей в objects).
> Негибко реализовано изменение классов моделей (Product, Offer и т.д.).
> 
> P.S. Удобная либа, но для базовых задач. Нужно добаивить больше гибкости.

Обновил версию b670e3a, ветка 2.0.x-dev
