### ISSUE TITLE
А как добавить событие на Документ

### ISSUE THREAD

**Issue by errogaht** [gillbeits/commerceml#4]
Привет! Спасибо, работает круто! я прям порадовался))
Но чувствую нужно будет заказы ещё парсить, они похоже в Документ
передаются, я как понял вы не стали делать так как там много разных типов?
Как на вашем пакете лучше сделать парсинг Документ ?

**Comment by gillbeits** [comment]
@errogaht на данный момент я не делал парсинг документов, да, там много типов, но это не проблема, - просто руки до этого не дошли. Когда делал либу, то такой задачи не стояло.
По хорошему, нужно сформировать модель для документа с нужными связями и сделать новое событие. Т.к. у меня в задачах на данный момент стоит обмен с 1с (снова), то в ближайшее время я как раз этим займусь. Заодно, скорее всего, выпущу и CommerceML Generator, т.к. нужна и обратная связь из web приложения с 1с.

Спасибо за внимание к данной библиотеке.

**Comment by errogaht** [comment]
Круто! я тоже как раз буду с 1с сейчас заниматься на работе наверное ближайшие месяца 3 - и нужно будет много всего по синхронизации. Есть ли смысл мне пулл реквесты делать? Ну в общем так, я начну с вашей библиотекой работать, и если вдруг что то полезное смогу сделать то предложу пулл реквест.

**Comment by gillbeits** [comment]
@errogaht если будет что-то полезное, то, несомненно, пулл реквест будет к месту!
